FROM python:3.7.6

#COPY .
#RUN cd post_classifier

#RUN ./download_data.sh

#RUN pip install -r requirements.txt

#CMD python source/main.py
# at runtime, see readme: python source/predict.py input/text.txt my_model


#1 clone git
#2 in local directory choose file which you want to run prediction on
#3. run sh <path to file> (build docker)
#4. (optional) 
#  i. change config in this dir
# ii. sh to recreate model
#iii. sh to rerun model

